### ISSUE TITLE
History duplication bug

### ISSUE THREAD

**Issue by JourneyOver** [trakt/Plex-Trakt-Scrobbler#232]
Well you told me to throw up the log for my issue with the history duplication and well here you go.

Most recent one
http://paste.ee/p/v3pkA

and another if you can't find any info in that one :x

this is a older file, the one above is the main one that has had a duplication happen.
http://paste.ee/p/YsfI8

Sorry they are super long and like most of the text in both are pretty much only numbers or IMDB or TVDB stuff, but hopefully you can find out the issue.. 

Sorry that I had to use a site to post them to, for some reason I couldn't attach the log at all to the issue itself and the text was so long that it was crashing my browser when ever I tried to paste it in here.

**Comment by fuzeman** [comment]
Sorry, forgot to mention you need to set the "Logging - Plugin" and "Logging - Libraries" options to "DEBUG" in the settings (at ```Channels -> trakt```), this will show more helpful messages in the log file when you run another sync.

----------------------

> Sorry that I had to use a site to post them to, for some reason I couldn't attach the log at all to the issue itself and the text was so long that it was crashing my browser when ever I tried to paste it in here.

All good, github doesn't handle long messages that well..

**Comment by JourneyOver** [comment]
Ah crap totally forgot to set those up a long time ago xD I'll get new logs for you next time I run into the duplication bug again.

**Comment by JourneyOver** [comment]
@fuzeman here you go, fresh from a sync, cought two different times that it synced two different shows twice.

newest file
http://paste.ee/p/ykSMK

and an older log just incase
http://paste.ee/p/RtlE7

**Comment by fuzeman** [comment]
It appears this issue is caused when plex returns two "stopped" notifications at the end of a video.

Will let you know when a fix is available to test.

---------------------------------------------

**Example:**
```
viewOffset  state
-------------------
0           playing
3309        paused
3309        paused
3309        playing
...
2542732     stopped
2542732     paused
2542732     stopped
```

**Comment by fuzeman** [comment]
Possible fix is available on the ```issue/232``` branch, download here: https://github.com/trakt/Plex-Trakt-Scrobbler/archive/issue/232.zip

Haven't reproduced the issue myself, so let me know if this fix works or not.

**Comment by JourneyOver** [comment]
Alright will do, it might be a couple days or so before I get back to you with an answer on if it fixed the issue or not.

**Comment by JourneyOver** [comment]
@fuzeman well that branch didn't fix the issue sadly, as I just recently got another scrobble duplication.

**Comment by fuzeman** [comment]
@JourneyOver can't see any duplicate "scrobble/stop" requests in that log file, these are the only scrobble actions in your log file:
```
2015-10-15 23:07:52,380 - Sending action u'scrobble/start' (account: <Account>, interface: u'scrobble', method: u'start')
2015-10-15 23:07:52,381 - request: {u'progress': 0.0, u'episode': {u'season': 3, u'number': 3, u'title': u'Blood and Fear'}, u'show': {u'title': u'Sleepy Hollow', u'ids': {u'tvdb': 269578}, u'year': 2015}}

2015-10-15 23:50:33,654 - Sending action u'scrobble/pause' (account: <Account>, interface: u'scrobble', method: u'pause')
2015-10-15 23:50:33,655 - request: {u'progress': 99.99, u'episode': {u'season': 3, u'number': 3, u'title': u'Blood and Fear'}, u'show': {u'title': u'Sleepy Hollow', u'ids': {u'tvdb': 269578}, u'year': 2015}}

2015-10-15 23:50:38,938 - Sending action u'scrobble/stop' (account: <Account>, interface: u'scrobble', method: u'stop')
2015-10-15 23:50:38,938 - request: {u'progress': 99.99, u'episode': {u'season': 3, u'number': 3, u'title': u'Blood and Fear'}, u'show': {u'title': u'Sleepy Hollow', u'ids': {u'tvdb': 269578}, u'year': 2015}}
```

Was Sleepy Hollow S03E03 the duplicated episode?

**Comment by JourneyOver** [comment]
Hmm that's kinda weird that it didn't show any duplicate scrobble/stop requests, Sleepy hollow s03e03 was one of the duplicated episodes that has happened when I uploaded those two logs, other one was the vampire diaries s07e02 but for some reason it didn't show up in the logs from what I can see..

whatever is causing the duplication stuff to happen has just been acting up more and more causing more and more shows to bring out duplicate scrobbles, but still it's not happening for every show/episode that I watch and every time it does do a duplicate scrobble it seems to always make the duplicate scrobble always exactly 2-4 minutes after the original one never more and never less..

I've tried cleaning plex of every trakt.tv thing as well to see if it was just left over files or something causing the issue but alas even after cleaning plex and it's folders of everything to do with trakt.tv and downloading a new copy and all that kinda stuff it still does it..

**Comment by JourneyOver** [comment]
@fuzeman heres another one that has happened.

http://paste.ee/p/LfBqM

this time only one log, the simpsons S27E04 is the one that has a duplicate (and I checked it to make sure even, and there is a duplicate scrobble/stop request).

**Comment by fuzeman** [comment]
Found another scrobble duplication issue in your log file, try update to the ```issue/232``` branch again ([issue/232.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/archive/issue/232.zip)).

**Comment by JourneyOver** [comment]
Alright will try and report back, got a few episodes of shows to catch up on so perfect time for testing :p

**Comment by JourneyOver** [comment]
@fuzeman  sadly that didn't fix it either :/

http://paste.ee/p/hAmXx

duplication for once upon a time s05e04.

**Comment by fuzeman** [comment]
Just pushed a couple more fixes (available in [issue/232.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/archive/issue/232.zip)), hopefully we are getting closer to a complete fix :smile:.

**Comment by xzKinGzxBuRnzx** [comment]
I think I'm having the same issue. I deleted a couple of these duplicate history items but here is a screenshot of whats happening.

![screen shot 2015-10-20 at 8 28 34 am](https://cloud.githubusercontent.com/assets/964415/10607011/9b9d3368-7704-11e5-9ea0-d528088de286.png)

[Here is a daily log](https://drive.google.com/file/d/0B-Oiqfh6qsDrbkxZREFVaTdkZGs/view?usp=sharing), which may help you in tracking it down. I was using the latest beta version and haven't tried any of the zip's you've provided above yet.

**Comment by pcjonathan** [comment]
I've had the same issue in the past. I'll keep an eye on it for the future but is there any way to fix this retroactively? Like possibly a script to go through my history and delete any duplicates? (I don't really care about multiple plays anyway.)

Because about a month ago, it went nuts to the point where there's far too many to simply delete individually, and I'd like to avoid having to go through it manually.

**Comment by JourneyOver** [comment]
so far haven't been able to test the new 232 update as it seems to not be able to reach the API or something, might be down possibly not sure..

>(hostname 'api-v2launch.trakt.tv' doesn't match either of 'ssl276353.cloudflaressl.com', '*.altorendimientoacademico.com', '*.baseshare.com', '*.campusqueretaro.net', '*.deeliciousfastfood.co.uk', '*.destinyrescue.org', '*.digitalbhoomi.com', '*.digitaldripped.com', '*.foerstehjaelpsshoppen.dk', '*.goodtimes.com.pk', '*.mobilewebsitesbyams.com', '*.nitexcite.com', '*.northaid.com', '*.parquetecnologico.mx', '*.spiritwear.com', '*.trakt.us', '*.vinoshipper.com', '*.watersidenursery.co.uk', '*.yellow.com.mt', 'altorendimientoacademico.com', 'baseshare.com', 'campusqueretaro.net', 'deeliciousfastfood.co.uk', 'destinyrescue.org', 'digitalbhoomi.com', 'digitaldripped.com', 'foerstehjaelpsshoppen.dk', 'goodtimes.com.pk',

**Comment by JourneyOver** [comment]
@fuzeman so far everything seems to be looking good now with the latest version of 232, watched 5 different things and each one of them only scrobbled once instead of having one or two of them scrobble twice like how it was happening before so this might possibly be fixed now. if I catch any duplications in the next day or two though I will let you know.

**Comment by xzKinGzxBuRnzx** [comment]
The issue is still occurring, although still very rare, it does happen. Can only guess it may be related to the errors effecting multiple events, which is...

```
2015-10-25 03:25:28,308 - plugin.managers.action           (7fb850fc4700) :  WARNING (plugin.managers.action:70) - Unable to queue event 'scrobble/start' for <Session session_key: u'27:2', state: 'start'>: ConstraintError: UNIQUE constraint failed: action.queue.session_id, action.queue.event
Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/managers/action.py", line 66, in queue
    queued_at=datetime.utcnow()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 4088, in create
    inst.save(force_insert=True)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 4235, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 2945, in execute
    cursor = self._execute()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 2455, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/playhouse/apsw_ext.py", line 106, in execute_sql
    raise
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 3009, in __exit__
    reraise(new_type, new_type(*exc_value.args), traceback)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/playhouse/apsw_ext.py", line 103, in execute_sql
    self._execute_sql(cursor, sql, params)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/playhouse/apsw_ext.py", line 95, in _execute_sql
    cursor.execute(sql, params or ())
  File "src/cursor.c", line 236, in resetcursor
IntegrityError: ConstraintError: UNIQUE constraint failed: action.queue.session_id, action.queue.event
```
[Full log available here.]( https://drive.google.com/file/d/0B-Oiqfh6qsDrdTcteXdYX0xmQzg/view?usp=sharing) The issue occurs at 03:24 - 03:25. I hope this helps.

**Comment by fuzeman** [comment]
@xzKinGzxBuRnzx It looks like there was a stop event at 86% watched:
```
2015-10-25 03:25:13,738 - Queued 'scrobble/stop' event for <Session session_key: u'27:1', state: 'stop'>
2015-10-25 03:25:17,044 - Sending action u'scrobble/stop' (account: <Account name: u'administrator'>, interface: u'scrobble', method: u'stop')
2015-10-25 03:25:17,044 - request: {u'progress': 86.09, u'episode': {u'season': 1, u'number': 10, u'title': u"Let's Save Central Florida! Let's Save Midtown!"}, u'show': {u'title': u'Blunt Talk', u'ids': {u'tvdb': 281181}, u'year': 2015}}
```

Then watching resumed as a 2nd session:
```
2015-10-25 03:25:19,450 - Queued 'scrobble/start' event for <Session session_key: '27:2', state: 'start'>
2015-10-25 03:25:22,568 - Sending action u'scrobble/start' (account: <Account name: u'administrator'>, interface: u'scrobble', method: u'start')
2015-10-25 03:25:22,568 - request: {u'progress': 86.09, u'episode': {u'season': 1, u'number': 10, u'title': u"Let's Save Central Florida! Let's Save Midtown!"}, u'show': {u'title': u'Blunt Talk', u'ids': {u'tvdb': 281181}, u'year': 2015}}
```

-------------------------------------

Fixing this issue might be a little complicated.. we will need to detect duplicate sessions on accounts for the same movie/episode and block the extra scrobbles from happening.

I'll post a comment here when there is a fix ready for testing *(possibly later this week)*

**Comment by fuzeman** [comment]
Was a bit busy last week, so just pushed a possible fix to the "issue/232" branch now. This fix means accounts can't scrobble the same item multiple times in an hour.

**Comment by xzKinGzxBuRnzx** [comment]
After a week or so of daily usage I've still not seen this bug occur again, appears to be fixed. Thanks!

**Comment by fuzeman** [comment]
@xzKinGzxBuRnzx That's good, getting closer to a stable release now :smile: *(just need to complete a few unfinished features)*.

**Comment by fuzeman** [comment]
Fixes released in [v0.9.10.12-beta](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v0.9.10.12-beta), let me know if you see any more cases of this happening.
