### ISSUE TITLE
Drobo5N

### ISSUE THREAD

**Issue by dhcrees** [trakt/Plex-Trakt-Scrobbler#303]
Hi,
I run my Plex server on a Drobo5N.  Does the plugin work with this configuration.   I've installed it and brought the server back up,  I'm getting the following errors in the log:

Apr 07, 2016 23:35:36 [0x33957400] WARN - Warning: Couldn't check file: /mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code
Apr 07, 2016 23:35:36 [0x33957400] WARN - Warning: Couldn't check file: /mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Info.plist
Apr 07, 2016 23:35:36 [0x33957400] WARN - Warning: Couldn't check file: /mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/fs_migrator.py
Apr 07, 2016 23:35:36 [0x33957400] WARN - Warning: Couldn't check file: /mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/__init__.py
Apr 07, 2016 23:35:36 [0x33957400] WARN - Warning: Couldn't check file: /mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/main.py

**Comment by fuzeman** [comment]
Did you update permissions after copying over the bundle?

1. Run this command to determine which user + group runs plex:

    ```
    stat --format '%U:%G' "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server"
    ```
    *It should return something like: ```plex:plex```*

2. Update owner + group of the plugin *(replace ```plex:plex``` with the output from step 1)*:

    ```
   sudo chown -R plex:plex "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle"
    ```

3. Update permissions

    ```
    sudo chmod -R 770 "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle"
    ```

**Comment by dhcrees** [comment]
Ok, my user was set to root:root,  so I followed the instructions and the only thing I see in the log now is

2016-04-09 11:55:13,673 - com.plexapp.plugins.trakttv      (2ad38210) :  CRITICAL (com.plexapp.plugins.trakttv:615) - Exception starting plug-in (most recent call last):
  File "/mnt/DroboFS/Shares/DroboApps/plex/Application/Resources/Plug-ins-ee6e505/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/core.py", line 608, in start
    self.sandbox.execute(self.init_code)
  File "/mnt/DroboFS/Shares/DroboApps/plex/Application/Resources/Plug-ins-ee6e505/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 256, in execute
    exec(code) in self.environment
  File "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/__init__.py", line 44, in <module>
    import interface
  File "/mnt/DroboFS/Shares/DroboApps/plex/Application/Resources/Plug-ins-ee6e505/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 333, in __import__
    return mod.load_module(_name)
  File "/mnt/DroboFS/Shares/DroboApps/plex/Application/Resources/Plug-ins-ee6e505/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 44, in load_module
    module = RestrictedModule(name, path, sandbox)
  File "/mnt/DroboFS/Shares/DroboApps/plex/Application/Resources/Plug-ins-ee6e505/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 30, in __init__
    exec(code) in self.__dict__
  File "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/interface/__init__.py", line 4, in <module>
    import m_sync
  File "/mnt/DroboFS/Shares/DroboApps/plex/Application/Resources/Plug-ins-ee6e505/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 333, in __import__
    return mod.load_module(_name)
  File "/mnt/DroboFS/Shares/DroboApps/plex/Application/Resources/Plug-ins-ee6e505/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 44, in load_module
    module = RestrictedModule(name, path, sandbox)
  File "/mnt/DroboFS/Shares/DroboApps/plex/Application/Resources/Plug-ins-ee6e505/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 30, in __init__
    exec(code) in self.__dict__
  File "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/interface/m_sync.py", line 8, in <module>
    from plugin.managers.account import AccountManager
  File "/mnt/DroboFS/Shares/DroboApps/plex/Application/Resources/Plug-ins-ee6e505/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 345, in __import__
    raise e
ImportError: No module named apsw

Not sure if this is correct or not?

If I go to http://trakt-for-plex.github.io/configuration

I can link it to my plex account, but when I click on my server I get spinning icon and then the message “HTTP Error: 500” is there some port I need to open, or am I missing something really obvious

Thanks in advance

**Comment by fuzeman** [comment]
I think this issue was fixed recently in the development branch.

Could you try this version of the plugin: https://github.com/trakt/Plex-Trakt-Scrobbler/archive/3c2cc78ee805c8bc8bd1c104279d3455ad26c035.zip

**Comment by dhcrees** [comment]
Unfortunately still getting the error:  Log details

2016-04-11 01:13:48,983 (2ad3c210) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: ee6e505 (Tue Apr 05 05:41:14 UTC 2016)
2016-04-11 01:13:48,985 (2ad3c210) :  DEBUG (core:361) - Using the elevated policy
2016-04-11 01:13:48,986 (2ad3c210) :  DEBUG (core:450) - Starting runtime component.
2016-04-11 01:13:48,995 (2ad3c210) :  DEBUG (core:450) - Starting caching component.
2016-04-11 01:13:48,997 (2ad3c210) :  DEBUG (core:450) - Starting data component.
2016-04-11 01:13:48,999 (2ad3c210) :  DEBUG (core:450) - Starting networking component.
2016-04-11 01:13:49,004 (2ad3c210) :  DEBUG (networking:282) - Loaded HTTP cookies
2016-04-11 01:13:49,007 (2ad3c210) :  DEBUG (networking:450) - Setting the default network timeout to 20.0
2016-04-11 01:13:49,012 (2ad3c210) :  DEBUG (core:450) - Starting localization component.
2016-04-11 01:13:49,014 (2ad3c210) :  INFO (localization:409) - Setting the default locale to en-us
2016-04-11 01:13:49,015 (2ad3c210) :  DEBUG (localization:427) - Loaded en strings
2016-04-11 01:13:49,017 (2ad3c210) :  DEBUG (core:450) - Starting messaging component.
2016-04-11 01:13:49,020 (2ad3c210) :  DEBUG (core:450) - Starting debugging component.
2016-04-11 01:13:49,021 (2ad3c210) :  DEBUG (core:450) - Starting services component.
2016-04-11 01:13:49,023 (2d97b470) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/com.plexapp.plugins.trakttv'
2016-04-11 01:13:49,024 (2ad3c210) :  DEBUG (core:450) - Starting myplex component.
2016-04-11 01:13:49,032 (2ad3c210) :  DEBUG (core:450) - Starting notifications component.
2016-04-11 01:13:50,536 (2ad3c210) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.plugins.trakttv in namespace 'metadata'
2016-04-11 01:13:50,588 (2ad3c210) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2016-04-11 01:13:50,733 (2d97b470) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2016-04-11 01:13:50,734 (2ad3c210) :  DEBUG (runtime:1117) - Created a thread named 'load_all_services'
2016-04-11 01:13:50,740 (2d97b470) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2016-04-11 01:13:50,741 (2ad3c210) :  DEBUG (runtime:1117) - Created a thread named 'get_server_info'
2016-04-11 01:13:50,746 (2e5f7470) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400'
2016-04-11 01:13:50,754 (2ad3c210) :  DEBUG (core:150) - Finished starting framework core
2016-04-11 01:13:50,760 (2ad3c210) :  DEBUG (core:560) - Loading plug-in code
2016-04-11 01:13:50,800 (2e5f7470) :  DEBUG (core:538) - Machine identifier is 005b8485a9118bb66f2bb6635514e54516cfb68a
2016-04-11 01:13:50,801 (2e5f7470) :  DEBUG (core:539) - Server version is 0.9.16.4.1911-ee6e505
2016-04-11 01:13:51,038 (2ad3c210) :  DEBUG (core:566) - Finished loading plug-in code
2016-04-11 01:13:51,154 (2ad3c210) :  DEBUG (__init__:18) - Using locale: C
2016-04-11 01:13:52,612 (2ad3c210) :  DEBUG (fs_migrator:19) - Running migration: <fs_migrator.Clean object at 0x8772f0>
2016-04-11 01:13:52,711 (2ad3c210) :  DEBUG (fs_migrator:19) - Running migration: <fs_migrator.ForceLegacy object at 0x877390>
2016-04-11 01:13:52,713 (2ad3c210) :  ERROR (fs_migrator:382) - Unable to find preferences file at "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-in Support/Preferences/com.plexapp.plugins.trakttv.xml", unable to run migration
2016-04-11 01:13:52,714 (2ad3c210) :  DEBUG (fs_migrator:19) - Running migration: <fs_migrator.SelectiveSync object at 0x8773b0>
2016-04-11 01:13:52,716 (2ad3c210) :  ERROR (fs_migrator:46) - Unable to find preferences file at "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-in Support/Preferences/com.plexapp.plugins.trakttv.xml", unable to run migration
2016-04-11 01:13:53,223 (2d97b470) :  DEBUG (services:362) - Loaded services
2016-04-11 01:13:53,312 (2df5b470) :  DEBUG (services:438) - No shared code to load
2016-04-11 01:13:54,174 - plugin.core.logger.handlers.error_reporter.ErrorReporter (2ad3c210) :  DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporter:201) - Configuring Raven for host: threaded+requests+http://cd67f74a7d114f1eb54369a0b1974dfa:a35053b58fc24bc98d7edbf8a440923e@sentry.skipthe.net:/1
2016-04-11 01:13:54,177 - plugin.core.logger.main          (2ad3c210) :  DEBUG (plugin.core.logger.main:68) - Initialized logging (report: True, storage: False)
2016-04-11 01:13:54,466 - plugin.core.configuration        (2ad3c210) :  DEBUG (plugin.core.configuration:33) - Parsing configuration file: 'Data/com.plexapp.plugins.trakttv/advanced.ini'
2016-04-11 01:13:54,470 - plugin.core.libraries.helpers.system (2ad3c210) :  INFO (plugin.core.libraries.helpers.system:190) - Executable at '' doesn't exist, using '/bin/ls' instead
2016-04-11 01:13:54,471 - plugin.core.libraries.helpers.system (2ad3c210) :  WARNING (plugin.core.libraries.helpers.system:215) - Unable to retrieve attributes from ELF '/bin/ls': Magic number does not match
Traceback (most recent call last):
  File "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/core/libraries/helpers/system.py", line 198, in elf_attributes
    elf = ELFFile(stream)
  File "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/elftools/elf/elffile.py", line 51, in __init__
    self._identify_file()
  File "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/elftools/elf/elffile.py", line 202, in _identify_file
    elf_assert(magic == b'\x7fELF', 'Magic number does not match')
  File "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/elftools/common/utils.py", line 69, in elf_assert
    _assert_with_exception(cond, msg, ELFError)
  File "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/elftools/common/utils.py", line 101, in _assert_with_exception
    raise exception_type(msg)
ELFError: Magic number does not match
2016-04-11 01:13:54,543 - plugin.core.logger.handlers.error_reporter.ErrorReporter (2ad3c210) :  DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporter:610) - Sending message of length 2124 to threaded+requests+http://sentry.skipthe.net/api/1/store/
2016-04-11 01:13:54,552 - plugin.core.libraries.helpers.system (2ad3c210) :  WARNING (plugin.core.libraries.helpers.system:86) - Unable to use ARM libraries, unsupported floating-point type?
2016-04-11 01:13:54,602 - plugin.core.logger.handlers.error_reporter.ErrorReporter (2ad3c210) :  DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporter:610) - Sending message of length 948 to threaded+requests+http://sentry.skipthe.net/api/1/store/
2016-04-11 01:13:54,603 - plugin.core.libraries.main       (2ad3c210) :  INFO (plugin.core.libraries.main:165) - Unable to cache libraries, using bundled libraries directly
2016-04-11 01:13:54,605 - plugin.core.libraries.main       (2ad3c210) :  INFO (plugin.core.libraries.main:36) - Using native libraries at 'Plug-ins/Trakttv.bundle/Contents/Libraries'
2016-04-11 01:13:54,608 - plugin.core.libraries.helpers.path (2ad3c210) :  DEBUG (plugin.core.libraries.helpers.path:45) - Removed path: 'Plug-ins/Trakttv.bundle/Contents/Libraries/Linux/armv5tel'
2016-04-11 01:13:54,612 - requests.packages.urllib3.connectionpool (2df5b470) :  INFO (requests.packages.urllib3.connectionpool:207) - Starting new HTTP connection (1): sentry.skipthe.net
2016-04-11 01:13:54,614 - plugin.core.libraries.main       (2ad3c210) :  DEBUG (plugin.core.libraries.main:177) - Bits: '32bit', Machine: 'armv7l'
2016-04-11 01:13:54,618 - plugin.core.libraries.helpers.system (2ad3c210) :  INFO (plugin.core.libraries.helpers.system:190) - Executable at '' doesn't exist, using '/bin/ls' instead
2016-04-11 01:13:54,620 - plugin.core.libraries.helpers.system (2ad3c210) :  WARNING (plugin.core.libraries.helpers.system:215) - Unable to retrieve attributes from ELF '/bin/ls': Magic number does not match
Traceback (most recent call last):
  File "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/core/libraries/helpers/system.py", line 198, in elf_attributes
    elf = ELFFile(stream)
  File "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/elftools/elf/elffile.py", line 51, in __init__
    self._identify_file()
  File "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/elftools/elf/elffile.py", line 202, in _identify_file
    elf_assert(magic == b'\x7fELF', 'Magic number does not match')
  File "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/elftools/common/utils.py", line 69, in elf_assert
    _assert_with_exception(cond, msg, ELFError)
  File "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/elftools/common/utils.py", line 101, in _assert_with_exception
    raise exception_type(msg)
ELFError: Magic number does not match
2016-04-11 01:13:54,667 - plugin.core.logger.handlers.error_reporter.ErrorReporter (2ad3c210) :  DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporter:610) - Sending message of length 2124 to threaded+requests+http://sentry.skipthe.net/api/1/store/
2016-04-11 01:13:54,669 - plugin.core.libraries.helpers.system (2ad3c210) :  WARNING (plugin.core.libraries.helpers.system:86) - Unable to use ARM libraries, unsupported floating-point type?
2016-04-11 01:13:54,676 - plugin.core.logger.handlers.error_reporter.ErrorReporter (2ad3c210) :  DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporter:610) - Sending message of length 948 to threaded+requests+http://sentry.skipthe.net/api/1/store/
2016-04-11 01:13:54,679 - plugin.core.libraries.main       (2ad3c210) :  INFO (plugin.core.libraries.main:51) - [PATH] Plug-ins/Trakttv.bundle/Contents/Libraries/Shared
2016-04-11 01:13:54,682 - plugin.core.libraries.main       (2ad3c210) :  INFO (plugin.core.libraries.main:56) - Testing native library support...
2016-04-11 01:13:54,685 - plugin.core.libraries.main       (2ad3c210) :  ERROR (plugin.core.libraries.main:66) - apsw: unavailable - Exception raised in 'test_import': No module named apsw
Traceback (most recent call last):
  File "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/core/libraries/tests/core/base.py", line 33, in run
    result = func()
  File "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/core/libraries/tests/apsw_.py", line 9, in test_import
    import apsw
ImportError: No module named apsw
2016-04-11 01:13:54,701 - plugin.core.logger.handlers.error_reporter.ErrorReporter (2ad3c210) :  DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporter:610) - Sending message of length 1556 to threaded+requests+http://sentry.skipthe.net/api/1/store/
2016-04-11 01:13:54,995 - requests.packages.urllib3.connectionpool (2df5b470) :  DEBUG (requests.packages.urllib3.connectionpool:387) - "POST /api/1/store/ HTTP/1.1" 200 None
2016-04-11 01:13:55,025 - requests.packages.urllib3.connectionpool (2df5b470) :  INFO (requests.packages.urllib3.connectionpool:207) - Starting new HTTP connection (1): sentry.skipthe.net
2016-04-11 01:13:55,370 - requests.packages.urllib3.connectionpool (2df5b470) :  DEBUG (requests.packages.urllib3.connectionpool:387) - "POST /api/1/store/ HTTP/1.1" 200 None
2016-04-11 01:13:55,401 - requests.packages.urllib3.connectionpool (2df5b470) :  INFO (requests.packages.urllib3.connectionpool:207) - Starting new HTTP connection (1): sentry.skipthe.net
2016-04-11 01:13:55,854 - requests.packages.urllib3.connectionpool (2df5b470) :  DEBUG (requests.packages.urllib3.connectionpool:387) - "POST /api/1/store/ HTTP/1.1" 200 None
2016-04-11 01:13:55,869 - requests.packages.urllib3.connectionpool (2df5b470) :  INFO (requests.packages.urllib3.connectionpool:207) - Starting new HTTP connection (1): sentry.skipthe.net
2016-04-11 01:13:55,874 - plugin.core.helpers              (2ad3c210) :  INFO (plugin.core.helpers:19) - Using 'simplejson' module for JSON serialization
2016-04-11 01:13:56,259 - requests.packages.urllib3.connectionpool (2df5b470) :  DEBUG (requests.packages.urllib3.connectionpool:387) - "POST /api/1/store/ HTTP/1.1" 200 None
2016-04-11 01:13:56,279 - requests.packages.urllib3.connectionpool (2df5b470) :  INFO (requests.packages.urllib3.connectionpool:207) - Starting new HTTP connection (1): sentry.skipthe.net
2016-04-11 01:13:56,655 - requests.packages.urllib3.connectionpool (2df5b470) :  DEBUG (requests.packages.urllib3.connectionpool:387) - "POST /api/1/store/ HTTP/1.1" 200 None
2016-04-11 01:13:57,205 - com.plexapp.plugins.trakttv      (2ad3c210) :  CRITICAL (com.plexapp.plugins.trakttv:615) - Exception starting plug-in (most recent call last):
  File "/mnt/DroboFS/Shares/DroboApps/plex/Application/Resources/Plug-ins-ee6e505/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/core.py", line 608, in start
    self.sandbox.execute(self.init_code)
  File "/mnt/DroboFS/Shares/DroboApps/plex/Application/Resources/Plug-ins-ee6e505/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 256, in execute
    exec(code) in self.environment
  File "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/__init__.py", line 44, in <module>
    import interface
  File "/mnt/DroboFS/Shares/DroboApps/plex/Application/Resources/Plug-ins-ee6e505/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 333, in __import__
    return mod.load_module(_name)
  File "/mnt/DroboFS/Shares/DroboApps/plex/Application/Resources/Plug-ins-ee6e505/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 44, in load_module
    module = RestrictedModule(name, path, sandbox)
  File "/mnt/DroboFS/Shares/DroboApps/plex/Application/Resources/Plug-ins-ee6e505/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 30, in __init__
    exec(code) in self.__dict__
  File "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/interface/__init__.py", line 4, in <module>
    import m_sync
  File "/mnt/DroboFS/Shares/DroboApps/plex/Application/Resources/Plug-ins-ee6e505/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 333, in __import__
    return mod.load_module(_name)
  File "/mnt/DroboFS/Shares/DroboApps/plex/Application/Resources/Plug-ins-ee6e505/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 44, in load_module
    module = RestrictedModule(name, path, sandbox)
  File "/mnt/DroboFS/Shares/DroboApps/plex/Application/Resources/Plug-ins-ee6e505/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 30, in __init__
    exec(code) in self.__dict__
  File "/mnt/DroboFS/Shares/DroboApps/plex/Library/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/interface/m_sync.py", line 8, in <module>
    from plugin.managers.account import AccountManager
  File "/mnt/DroboFS/Shares/DroboApps/plex/Application/Resources/Plug-ins-ee6e505/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 345, in __import__
    raise e
ImportError: No module named apsw

2016-04-11 01:13:57,678 - plugin.core.logger.handlers.error_reporter.ErrorReporter (2ad3c210) :  DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporter:610) - Sending message of length 3276 to threaded+requests+http://sentry.skipthe.net/api/1/store/
2016-04-11 01:13:57,688 - requests.packages.urllib3.connectionpool (2df5b470) :  INFO (requests.packages.urllib3.connectionpool:207) - Starting new HTTP connection (1): sentry.skipthe.net
2016-04-11 01:13:58,055 - requests.packages.urllib3.connectionpool (2df5b470) :  DEBUG (requests.packages.urllib3.connectionpool:387) - "POST /api/1/store/ HTTP/1.1" 200 None

**Comment by fuzeman** [comment]
Looks like there is an issue with ARM float-type detection, will try have a fix (or workaround) available tomorrow.

**Comment by dhcrees** [comment]
Many thanks for your help with this.

**Comment by fuzeman** [comment]
I've implemented a possible workaround for this issue, try these steps:

1. Install this version of the plugin: https://github.com/fuzeman/Plex-Trakt-Scrobbler/archive/issue/303.zip

2. Create the ```Plug-in Support/Data/com.plexapp.plugins.trakttv/advanced.ini``` with these contents:

    ```
    [libraries]
    arm_float_type=hf
    ```

3. Restart Plex Media Server

**Comment by dhcrees** [comment]
It seems to be getting further I have linked my trakt.tv account and I can see what I'm watching on the trakt.tv website, but I'm not sure if its working properly. There are still some odd looking things in the log.

[com.plexapp.plugins.trakttv.log.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/files/215802/com.plexapp.plugins.trakttv.log.zip)

**Comment by fuzeman** [comment]
Glad it's working now :smile:

I don't see any critical issues with the plugin in your log files, I'll explain some of the messages below.

--------------------

```
Unsupported service: none
```
This warning indicates you have unmatched media in one of your Plex libraries. *(media that couldn't be found on IMDb or TheTVDB)*

-------------

```
Invalid "title" or "year" attribute on <u'Salem' (None)>
```
This show/movie doesn't have a valid "year", and so can't be added to your Trakt.tv profile. Refreshing the show/movie via Plex/Web should fix this.

----------------------------------

```
Exception raised in run(): HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /sync/history (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Read timed out. (read timeout=24)",))
```
The Trakt.tv API timed out during a request, you might need to try another sync to bring your Trakt.tv profile up to date.

**Comment by dhcrees** [comment]
Thanks again for the help.  Am I using a development version now or can I install the plug in from master? was it the advanced.ini settings that fixed it or is there something thats yet to be merged into the main branch, how will I find out if thats the case, so I know when to upgrade?

**Comment by fuzeman** [comment]
Yeah, you will need to continue using the development branch for now. I'll post a comment in this issue when the changes have been released in a stable version *(possibly later today)*.

**Comment by fuzeman** [comment]
Changes released in [v1.0.2.0](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.0.2.0)

**Comment by marknsikora** [comment]
The advanced.ini fix is still required to get this running on a drobo5n. Maybe a section should be added to the FAQ for people who don't have the ability to debug the issue themselves.

**Comment by fuzeman** [comment]
@marknsikora Thanks for reminding me about this issue :smile:

The [Drobo](https://github.com/fuzeman/Plex-Trakt-Scrobbler/wiki/Installation%20-%20Drobo) installation page on the development version of the wiki now includes details on that fix, it will be released to the master version of the wiki (at `trakt/Plex-Trakt-Scrobbler`) next month.
