### ISSUE TITLE
Plex Trakt Scrobbler is not working.

### ISSUE THREAD

**Issue by rickytin** [trakt/Plex-Trakt-Scrobbler#372]
Plex Trakt Scrobbler is not working, It was working perfect until I did yesterday Plex Media Server update Version 1.3.0.3059-6277334 for Windows. I have reinstall the master version without success so I try develop but still not working.  

Thanks and Happy Thanksgiving day.

**Comment by Tommatheussen** [comment]
Confirmed, scrobbling won't work on Ubuntu either after update to 1.3. Attached is a partial debug logging:

```
2016-11-24 21:12:37,364 - plex.objects.core.base           (-549fa4c0) :  WARNING (plex.objects.core.base:156) - [Detail] Omitted attribute: photoautotag
2016-11-24 21:12:37,364 - plex.objects.core.base           (-549fa4c0) :  WARNING (plex.objects.core.base:156) - [Detail] Omitted attribute: voicesearch
2016-11-24 21:13:07,405 - plex_activity.sources.s_logging.main (-549fa4c0) :  INFO (plex_activity.sources.s_logging.main:84) - Unable to read log file
2016-11-24 21:13:37,443 - requests.packages.urllib3.connectionpool (-549fa4c0) :  DEBUG (requests.packages.urllib3.connectionpool:249) - Resetting dropped connection: 127.0.0.1
2016-11-24 21:13:37,449 - requests.packages.urllib3.connectionpool (-549fa4c0) :  DEBUG (requests.packages.urllib3.connectionpool:401) - "GET / HTTP/1.1" 200 2551
2016-11-24 21:13:37,455 - plex.objects.core.base           (-549fa4c0) :  WARNING (plex.objects.core.base:156) - [Detail] Omitted attribute: photoautotag
2016-11-24 21:13:37,455 - plex.objects.core.base           (-549fa4c0) :  WARNING (plex.objects.core.base:156) - [Detail] Omitted attribute: voicesearch
2016-11-24 21:14:07,496 - plex_activity.sources.s_logging.main (-549fa4c0) :  INFO (plex_activity.sources.s_logging.main:84) - Unable to read log file
2016-11-24 21:14:42,590 - requests.packages.urllib3.connectionpool (-549fa4c0) :  DEBUG (requests.packages.urllib3.connectionpool:249) - Resetting dropped connection: 127.0.0.1
2016-11-24 21:14:42,596 - requests.packages.urllib3.connectionpool (-549fa4c0) :  DEBUG (requests.packages.urllib3.connectionpool:401) - "GET / HTTP/1.1" 200 2551
2016-11-24 21:14:42,602 - plex.objects.core.base           (-549fa4c0) :  WARNING (plex.objects.core.base:156) - [Detail] Omitted attribute: photoautotag
2016-11-24 21:14:42,602 - plex.objects.core.base           (-549fa4c0) :  WARNING (plex.objects.core.base:156) - [Detail] Omitted attribute: voicesearch
2016-11-24 21:15:12,642 - plex_activity.sources.s_logging.main (-549fa4c0) :  INFO (plex_activity.sources.s_logging.main:84) - Unable to read log file
2016-11-24 21:15:42,680 - requests.packages.urllib3.connectionpool (-549fa4c0) :  DEBUG (requests.packages.urllib3.connectionpool:249) - Resetting dropped connection: 127.0.0.1
2016-11-24 21:15:42,686 - requests.packages.urllib3.connectionpool (-549fa4c0) :  DEBUG (requests.packages.urllib3.connectionpool:401) - "GET / HTTP/1.1" 200 2551
2016-11-24 21:15:42,692 - plex.objects.core.base           (-549fa4c0) :  WARNING (plex.objects.core.base:156) - [Detail] Omitted attribute: photoautotag
2016-11-24 21:15:42,693 - plex.objects.core.base           (-549fa4c0) :  WARNING (plex.objects.core.base:156) - [Detail] Omitted attribute: voicesearch
2016-11-24 21:16:29,902 - requests.packages.urllib3.connectionpool (-549fa4c0) :  DEBUG (requests.packages.urllib3.connectionpool:249) - Resetting dropped connection: 127.0.0.1
2016-11-24 21:16:29,909 - requests.packages.urllib3.connectionpool (-549fa4c0) :  DEBUG (requests.packages.urllib3.connectionpool:401) - "GET / HTTP/1.1" 200 2551
2016-11-24 21:16:29,915 - plex.objects.core.base           (-549fa4c0) :  WARNING (plex.objects.core.base:156) - [Detail] Omitted attribute: photoautotag
2016-11-24 21:16:29,916 - plex.objects.core.base           (-549fa4c0) :  WARNING (plex.objects.core.base:156) - [Detail] Omitted attribute: voicesearch
2016-11-24 21:16:59,954 - plex_activity.sources.s_logging.main (-549fa4c0) :  INFO (plex_activity.sources.s_logging.main:84) - Unable to read log file
2016-11-24 21:17:29,991 - requests.packages.urllib3.connectionpool (-549fa4c0) :  DEBUG (requests.packages.urllib3.connectionpool:249) - Resetting dropped connection: 127.0.0.1
2016-11-24 21:17:29,999 - requests.packages.urllib3.connectionpool (-549fa4c0) :  DEBUG (requests.packages.urllib3.connectionpool:401) - "GET / HTTP/1.1" 200 2551
2016-11-24 21:17:30,007 - plex.objects.core.base           (-549fa4c0) :  WARNING (plex.objects.core.base:156) - [Detail] Omitted attribute: photoautotag
2016-11-24 21:17:30,008 - plex.objects.core.base           (-549fa4c0) :  WARNING (plex.objects.core.base:156) - [Detail] Omitted attribute: voicesearch
```

**Comment by fuzeman** [comment]
Thanks for reporting this, will try have a fix released later today.

**Comment by fuzeman** [comment]
Fix is available on the [develop](https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip) branch now, will be releasing this fix in a new stable release later today.

**Comment by fuzeman** [comment]
Fix released in [v1.1.0.7](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.1.0.7)

**Comment by rsanch1** [comment]
Still not working. I'm on v1.1.0.7-master.

[Exception]HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries

**Comment by fuzeman** [comment]
@rsanch1 That looks like a Trakt.tv API connection issue, can't identify exactly what is causing that error without the full plugin log file though.. It might be just an intermittent fault with Trakt.tv, CloudFlare or your network..
